### ISSUE TITLE
Tab key not converting unicode to symbol

### ISSUE THREAD

**Issue by jfimbett** [JunoLab/atom-latex-completions#36] opened 2018-12-20 01:43 UTC
Hello, I recently updated the packages for Juno but Im having troubles in using the Tab key to autocomplete, even simple things

When I type \alpha, and I press TAB key, instead of inserting the symbol, Juno makes a tab space

Also when I type greek letters, no matter which one \alpha tends to appear always first, but if I unselect the boost greek characters, I have some other unicode characters not related appearing as suggestions for greek letters. 

My guess is that when I updated latex-completitions something got messed

Thank you

**Comment by pfitzseb** [comment] 2018-12-20 08:35
This is a duplicate of #34 and #35 -- just call `pkg> update` in a Julia session and restart Atom.

Should also be fixed (in a different way) with https://github.com/JunoLab/atom-latex-completions/commit/4386f2d3be24b8f716cfc78004b597f358cd4cf8.

**Closed as completed by pfitzseb** 2018-12-20 08:35 UTC
